Dz1
osipowvw/2024-2-VK-EDU-Frontend-M-Osipov pull request #3
Opened 2024-09-20 13:00 UTC by osipowvw

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @kernel проверить его.

Что было сделано:
* Сделаны функции из ДЗ
* Модифицированы тест для функций

2024-09-20 14:41 UTC, nelkor requested changes
Есть одна критическая проблема, а .gitignore можно поправить или нет на своё усмотрение.

2024-09-20 14:41 UTC, nelkor commented on .gitignore
> +.lesshst
Директории `.git` точно не должно быть в `.gitignore`. Остальное, гипотетически, можно, но по хорошему тоже не должно быть. Впрочем, можно и оставить, ничего страшного не случится.

2024-09-20 14:41 UTC, nelkor commented on dz1/convertBytesToHuman.test.js
> +test('Возвращает корректное значение для чисел', () => {
Нет ни одной проверки на один знак после точки. Должна быть обязательно.

2024-09-23 08:30 UTC, nelkor approved these changes

2024-09-25 20:50 UTC, martinkomitsky approved these changes
12!

2024-09-25 20:50 UTC, merged