Hw2
osipowvw/2024-2-VK-EDU-Frontend-M-Osipov pull request #4
Opened 2024-09-30 14:46 UTC by osipowvw

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @kernel проверить его.

Что было сделано:
* Сделан первоначальный внешний вид приложения по макету
* Стилизована форма отправки сообщений
* Установлены иконки Google Icons
* Реализованы все функции, упомянутые в дз
* Настроен Deploy на GitHub Pages

2024-10-02 07:06 UTC, nelkor requested changes
Что-то не вижу нигде ссылки на GitHub Pages. Такое чувство, что сборка не отработала. В любом случае, добавь ссылку в комментарий.

2024-10-02 07:06 UTC, nelkor commented on .gitignore
> +vk-edu-frontend/
Ого, а что там лежит?

2024-10-02 07:06 UTC, nelkor commented on .gitignore
> +simple-chat/build
Вот так если исправить, в любой поддиректории будут игнорироваться `node_modules` и `build`.

```suggestion
node_modules
build
```

2024-10-02 07:06 UTC, nelkor commented on simple-chat/package.json
> +    "build": "webpack --mode=development"
Собирать надо с модом продакшен.

```suggestion
    "build": "webpack --mode=production"
```

2024-10-02 07:06 UTC, nelkor commented on simple-chat/package.json
> +    "webpack": "^4.41.0",
Почему такая старая версия?

2024-10-02 12:25 UTC, nelkor commented on .gitignore
> +simple-chat/build
Я ведь не так написал.

2024-10-02 12:27 UTC, nelkor requested changes
Одна из ошибок не исправлена. Нет ссылки на развёрнутое приложение.

2024-10-02 12:27 UTC, nelkor commented on package.json
А этот файл зачем?

2024-10-02 12:41 UTC, nelkor requested changes
Должна быть возможность писать сообщения от лица разных пользователей. Свои сообщения должны быть визуально отделены от чужих. Например, в твоём случае, ты можешь добавить кнопку смены Дженнифер на её собеседника.

2024-10-03 13:04 UTC, nelkor requested changes
Когда переключаешь пользователя, сообщения Дженнифер должны стать "твоими", потому что мы как бы её телефон видим в этот момент.

К коду претензий нет.

2024-10-03 13:31 UTC, nelkor approved these changes

2024-10-03 18:07 UTC, HaseProgram approved these changes
12

2024-10-03 18:07 UTC, merged