Hw3
osipowvw/2024-2-VK-EDU-Frontend-M-Osipov pull request #5
Opened 2024-10-13 16:30 UTC by osipowvw

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @kernel проверить его.

Что было сделано:
* Декомпозирован макет на маленькие части.
 - Шапка (с кнопкой поиска, заголовком, кнопкой "бургер")
 - Чат (с аватаром, заголовком, последним сообщением, временем и индикатором прочитанности/доставленности)
 - "Парящая" кнопка "создать чат"
gh-pages: https://osipowvw.github.io/2024-2-VK-EDU-Frontend-M-Osipov/

2024-10-14 11:48 UTC, nelkor requested changes
Приложение не работает. Отправляю сообщение, и его просто нет.

2024-10-14 11:55 UTC, nelkor requested changes
Первая проблема исправлена. Далее:
- Всегда написано "Нет сообщений", даже если они есть.
- Создал второй чат, в нём нажал стрелочки — увидел сообщения из первого чата.

2024-10-17 14:54 UTC, nelkor approved these changes
Время в сообщениях неплохо бы писать отдельной строкой, иначе вид сообщения ломается. Но это и не критично.

2024-10-19 12:25 UTC, merged

2024-10-19 12:25 UTC, martinkomitsky commented
7